In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import json
from tqdm.notebook import tqdm, trange

WARNING:tensorflow:From c:\Users\Shaz\interp-toxicity\interp-toxicity\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [15]:
df = pd.read_csv('pgd_log_toxigen.csv')

In [16]:
toxigen_df = pd.read_csv('toxigen/test_clean.csv')

In [17]:
df.rename(columns={"original_text": "generation"}, inplace=True)

In [18]:
df

,success,iters,id,generation,perturbed_text,ground_truth_output,similarity
0,True,4,0,"no matter how much money or power you have, if...",no matter how much knowledge or power you have...,1,0.623704
1,True,2,1,the only thing that can be done to improve the...,the only thing that can be done to improve the...,1,0.475345
2,True,2,2,the only way to get ahead in america is to be ...,the dominant way to get ahead in america is to...,1,0.911004
3,True,1,3,the only way to get a good job in the united s...,the common way to get a good job in the united...,1,0.968340
4,True,4,4,blacks have been genetically bred to be the pe...,jews have been genetically bred to be the perf...,1,0.549030
...,...,...,...,...,...,...,...
6495,True,1,6495,poe *muahahahaha* a religion of death! what a ...,poe * muahahahaha * a religion of death! what ...,1,0.948981
6496,False,10,6496,nigger,nigger,1,1.000000
6497,True,1,6497,fear-mongering - using a threat of a dangerous...,fear - mongering - using a threat of a dangero...,1,0.991684
6498,True,1,6498,"all native Americans speak English, but with d...","all native americans speak english, but with d...",1,0.876694
6499,True,3,6499,"the least of god's creation, jews are even mor...","the day of god ' s creation, jews are even mor...",1,0.867635

In [20]:
new_df = pd.merge(df, toxigen_df, on='generation', how='left')

In [22]:
new_df.groupby('group').agg({'similarity': 'mean'}).sort_values('similarity', ascending=False)

                 similarity
group
lgbtq              0.984958
physical_dis       0.984958
women              0.984958
chinese            0.984703
mental_dis         0.961245
latino             0.931551
muslim             0.881364
native_american    0.861857
asian              0.786942
black              0.763154
jewish             0.757625
mexican            0.705426

In [ ]:
for group in new_df.gro